### ISSUE TITLE
how do I install this on ubuntu?

### ISSUE THREAD

**Issue by ghost** [Rick-Moba/rtl8192cu#2]
Hi I was wondering if I could build this and install it on Ubuntu I was using Manjaro at the time now I using Ubuntu I was wondering where I could find documentation on installing it in Ubuntu kernel 4.19

**Comment by Rick-Moba** [comment]
Hi, this is the source code of the driver, it's valid for all distributions, with this you should follow the guidelines for ubuntu to add a DKMS module with this source.
